### PR TITLE
Add Austrian National Library - Department Research and Development

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
@gpetz, please review. We are also happy to accept pull requests which add people from your team.

**Comment by stweil** [comment]
Perhaps we should also split that block into three parts. That makes it a little bit easier. There still remains the question about the sort criteria: local name, English name, country, city?

There are also open issues which suggest to add more information to the single entries. If we convert all data to JSON, that would allow flexible automated sorting.

**Comment by zuphilip** [comment]
These are all good questions and suggestions. But until we have resolved them I suggest to continue as before.

BTW I would envision that we have a simple list of GitHub names and the other information will be added by some calls of the GitHub API.

**Comment by stweil** [comment]
@zuphilip, now updated according to your suggestion.

**Comment by zuphilip** [comment]
Thank you @stweil !

**Pull request merged**
