### PR TITLE
Add Timotheus Chang-whae Kim

### PR DESCRIPTION
**Pull request by zuphilip**
CC @socheres

### CODE REVIEW

**Comment by hbunke** [comment]
Sorry for being late with merging thist, vacation....

**Comment by zuphilip** [comment]
@hbunke No problem. But it looks for me that you did just close the pull request and not merged it? Do we need now a [new PR](https://github.com/hbunke/BibsOnGitHub/compare/master...zuphilip:patch-1?expand=1) or can you still accept it?

**Comment by hbunke** [comment]
uuuuh... it's hard after being four weeks off. Sorry.

**Comment by zuphilip** [comment]
Thank you!

**Pull request merged**
