### PR TITLE
Add digibib (Oslo) and AKBibliothekWien

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by stweil** [comment]
Should we use the local names for institutions? Most German institutions were added with their German names.  I personally prefer local names – the English name could be added in parentheses if the local name is too complicated for foreign readers (non Latin letters, ...).

**Comment by zuphilip** [comment]
I just copied the description from their page...

**Comment by stweil** [comment]
That sounds reasonable.

**Comment by hbunke** [comment]
I guess we should just derive the title from the GitHub account, so let the institutions themselves decide. I won't object to add an english title in case of some weird non-latin characters or whatever, but then it should also be an official one.

**Pull request merged**
