### PR TITLE
Add MDZ, J. Baiter

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
@jbaiter, could you please review this pull request (and maybe add your colleagues, too)?

**Comment by jbaiter** [comment]
Sure thing!

Here are the entries for the other developers from my department with an active presence on GitHub:

```
Marcus Bitzl (MDZ)
[https://github.com/orgs/dbmdz/people/bitzl](https://github.com/orgs/dbmdz/people/bitzl)

Ralf Eichinger (MDZ)
[https://github.com/orgs/dbmdz/people/datazuul](https://github.com/orgs/dbmdz/people/datazuul)

Matthias Lindinger (MDZ)
[https://github.com/orgs/dbmdz/people/morpheus-87](https://github.com/orgs/dbmdz/people/morpheus-87)

Christoph Lorenz (MDZ)
[https://github.com/orgs/dbmdz/people/clorenz](https://github.com/orgs/dbmdz/people/clorenz)

Doris Peter (MDZ)
[https://github.com/orgs/dbmdz/people/DorisPeter](https://github.com/orgs/dbmdz/people/DorisPeter)
```

**Comment by stweil** [comment]
Thanks. I added a commit for @bitzl, @datazuul, @morpheus-87, @clorenz and @DorisPeter now.

**Comment by hbunke** [comment]
Thx all!

**Pull request merged**
