### PR TITLE
UB der TU Hamburg (Gitlab is primary repository)

### PR DESCRIPTION
**Pull request by tzeumer**
We have Gitlab and Github, but Gitlab has become our primary choice for new projects.

### CODE REVIEW

**Comment by tzeumer** [comment]
Sorry, I obviously didn't read it carefully enough. The repository is managed by the university and it is encouraged to use it instead of commercial services like (explicitly mentioned) Github. But it's not a problem if it's removed.

**Comment by hbunke** [comment]
Sorry for being late here. I would be very much in favour of limiting ourselves to GitHub and GitLab. The institutional instances often and for the most part contain private repositories or those where access is selective (collaborative projects etc.). The original idea of our repository was to create a centralised network on a public, well-known and established platform. And, of course, forking should be as easy as possible. It also may not be too much effort to run GitHub and the institutional repo, we do it that way at TIB, for example.

**Comment by tzeumer** [comment]
It is no problem. We had set a "See also https://collaborating.tuhh.de/tub/" note at https://github.com/tubhh when our Gitlab became the main repository. And a few things are still updated at Github.

**Comment by stweil** [comment]
Then let us close this pull requests. @tzeumer, if you want you can also add persons from TU Hamburg to the list.

**Pull request closed without merging**
